apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.helloworld.deploymentName }}
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: {{ .Values.helloworld.podName }}
          image: {{ .Values.helloworld.image }}
