{{- if .Values.captain.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: captain
  labels:
    {{- include "AGH2-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: captain
  template:
    metadata:
      labels:
        app: captain
    spec:
      initContainers:
        - name: captain-init-redis
          image: registry.lkc-lab.com/docker/library/redis:6-alpine
          command:
            [
              "sh",
              "-c",
              "until redis-cli --no-auth-warning -h $REDIS_SERVICE_HOST -p $REDIS_SERVICE_PORT ping; do echo waiting for redis; sleep 1; done",
            ]
        - name: captain-init-postgresql
          image: postgres:13
          env:
            - name: PG_CONN_STR
              valueFrom:
                secretKeyRef:
                  key: DB_CONN_STR
                  name: capt-db-secret
          command:
            [
              "sh",
              "-c",
              "until pg_isready -d $PG_CONN_STR; do echo waiting for postgresql; sleep 1; done",
            ]
      containers:
        - name: captain
          image: "{{ .Values.captain.image.repository}}:{{ .Values.captain.image.tag }}"
          command:
            - ./captain
          env:
            - name: DB_Conn
              valueFrom:
                secretKeyRef:
                  key: DB_CONN_STR
                  name: capt-db-secret
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CORE_URL
              value: "core.$(NAMESPACE).svc.cluster.local:50005"
            - name: EXPMGR_URL
              value: "exploitmgr.$(NAMESPACE).svc.cluster.local:50005"
            - name: TEMPLATE_URL
              value: "template.$(NAMESPACE).svc.cluster.local:50005"
            - name: MINIO_URL
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: url
            - name: Addr
              value: ":9527"
            - name: SECRET_JWT
              valueFrom:
                secretKeyRef:
                  name: capt-jwt-secret
                  key: jwt-secret
            - name: "KEYGEN_ACCOUNT_ID"
              valueFrom:
                secretKeyRef:
                  name: capt-keygen-secret
                  key: account-id
            - name: "KEYGEN_API_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: capt-keygen-secret
                  key: api-token
            - name: MINIO_USER
              valueFrom:
                secretKeyRef:
                  name: capt-minio-secret
                  key: capt-minio-user
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: capt-minio-secret
                  key: capt-minio-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 9527
          imagePullPolicy: {{ .Values.captain.image.pullPolicy }}
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: "Always"
{{- end }}