{{- if .Values.exploitmgr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exploitmgr
  labels:
    {{- include "AGH2-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: exploitmgr
  template:
    metadata:
      labels:
        app: exploitmgr
    spec:
      initContainers:
        - name: exploitmgr-init-postgresql
          image: postgres:13
          env:
            - name: PG_CONN_STR
              valueFrom:
                secretKeyRef:
                  key: DB_CONN_STR
                  name: expmgr-db-secret
          command:
            [
              "sh",
              "-c",
              "until pg_isready -d $PG_CONN_STR; do echo waiting for postgresql; sleep 1; done",
            ]
      containers:
        - name: exploitmgr
          image: "{{ .Values.exploitmgr.image.repository }}:{{ .Values.exploitmgr.image.tag }}"
          command:
            - ./exploitmgr
          env:
            - name: DB_Conn
              valueFrom:
                secretKeyRef:
                  key: DB_CONN_STR
                  name: expmgr-db-secret
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CORE_URL
              value: "core.$(NAMESPACE).svc.cluster.local:50005"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - name: grpc
              containerPort: 50005
          imagePullPolicy: {{ .Values.exploitmgr.pullPolicy }}
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always
{{- end }}