{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "AGH2-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - name: web
              containerPort: 80
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
      imagePullSecrets:
        - name: gitlab-registry
      restartPolicy: Always
{{- end }}