apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry
  labels:
    {{- include "AGH2-helm.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}